### ISSUE TITLE
nest start doesn't wait for app to exit

### ISSUE THREAD

**Issue by WiseBird** [nestjs/nest-cli#1615] opened 2022-04-18 12:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

CLI doesn't wait for the application to exit.
In the case of closing CLI with Ctrl-C, it results in the application still running (and logging messages) while control is returned to the terminal.
![image](https://user-images.githubusercontent.com/1745378/163806595-e686c835-17e5-457a-a93c-f898d45641b4.png)

In the case of the watch command, the application is restarted before the previous instance is stopped, which results in `address already in use` error.
![image](https://user-images.githubusercontent.com/1745378/163806666-24ea4f6e-f075-4ce3-bbd7-493a435d62c6.png)

### Minimum reproduction code

https://github.com/WiseBird/nestjs-shutdown

### Steps to reproduce

From a code perspective, the app should have an async shutdown hook, e.g.:
![image](https://user-images.githubusercontent.com/1745378/163806868-20e9e31e-a182-4c3c-a92a-7207df96edf4.png)

The simplest steps:
1. `npm start`
2. Ctrl+C

could be also reproduced with `start:dev` command:
1. `npm run start:dev`
2. Make a change in the code

### Expected behavior

CLI waits for the application to exit before exiting itself or restarting the app.

### Package version

8.2.5

### NestJS version

8.4.4

### Node.js version

16.10.

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

The problem relates to #1487, not sure if it can be considered a duplicate as this one is not about http server but purely CLI issue.

**Comment by micalevisk** [comment] 2022-04-18 12:55
duplicate of #1614

**Closed** 2022-04-18 14:10 UTC
Labels: bug, needs triage
