### ISSUE TITLE
"nest g resource" is not choosing the right package manager

### ISSUE THREAD

**Issue by ianzone** [nestjs/nest-cli#1672] opened 2022-06-04 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a pnpm-lock.yaml file in the project root directory. When I try to generate a user resource, nest was using npm to install the @nestjs/mapped-types, which caused the following error.

```
❯ nest g resource user
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/user/user.controller.spec.ts (556 bytes)
CREATE src/user/user.controller.ts (883 bytes)
CREATE src/user/user.module.ts (240 bytes)
CREATE src/user/user.service.spec.ts (446 bytes)
CREATE src/user/user.service.ts (607 bytes)
CREATE src/user/dto/create-user.dto.ts (30 bytes)
CREATE src/user/dto/update-user.dto.ts (169 bytes)
CREATE src/user/entities/user.entity.ts (21 bytes)
UPDATE package.json (2055 bytes)
UPDATE src/app.module.ts (308 bytes)
⠸ Installing packages (npm)...npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ian/.npm/_logs/2022-06-04T14_31_04_269Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

Failed to execute command: node @nestjs/schematics:resource --name=user --no-dry-run --no-skipImport --language="ts" --sourceRoot="src" --spec
```

### Minimum reproduction code

see 'Steps to reproduce'

### Steps to reproduce

1. `nest new Proj --package-manager pnpm --skip-install --strict`
2. `cd Proj`
3. `pnpm i`
4. `nest g resource user`
5. `What transport layer do you use? REST API`
6. `Would you like to generate CRUD entry points? Yes`

### Expected behavior

nest should detect the pnpm-lock.yaml and automatically use pnpm to install dependencies.

### Package version

8.2.6

### NestJS version

8.4.6

### Node.js version

18.3.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by iamshabell** [comment] 2022-06-04 16:03
I think this issue related to this issue #1115

**Comment by kamilmysliwiec** [comment] 2022-06-14 08:16
Duplicate of https://github.com/nestjs/nest-cli/issues/1115

**Closed by kamilmysliwiec** 2022-06-14 08:16 UTC
Labels: bug, needs triage
