### ISSUE TITLE
[BUG] - Generate Command Error

### ISSUE THREAD

**Issue by John0x** [nestjs/nest-cli#55] opened 2018-01-27 17:54 UTC
Hey, I'm inside a freshly generated nest project (generated by the cli) and tried to run ``nest g module test``, which gives me this error:
````
ENOENT: no such file or directory, mkdir 'D:\D:\D:'
````

Windows 10 (newest updates)
64bit

**Comment by ThomRick** [comment] 2018-01-28 10:18
Hum super weird about the mkdir error !
I'll check it out soon

**Comment by ChaoticLoki** [comment] 2018-02-28 09:18
Seems to be an issue with the reducer in the function `createRecursiveDirectory(folder)` in the `./src/commands/generate/asset.emitter.ts` file.

**Comment by ThomRick** [comment] 2018-02-28 10:17
Hey @ChaoticLoki 
I'll reproduce the issue also 

It will be fixed soon with the @angular-devkit/schematics template engine !!!

**Comment by zanjs** [comment] 2018-03-21 06:03
I'll reproduce the issue also @ChaoticLoki  😭😭😭😭

**Comment by weeco** [comment] 2018-03-27 03:08
Same issue here, I am available in case you need more information to debug.

**Comment by ThomRick** [comment] 2018-04-01 10:31
The CLI tool was rebuild from scratch and integrate schematics to generate assets.
Please upgrade to v4.0.0-rc1

**Closed by ThomRick** 2018-04-01 10:31 UTC
Labels: bug
