### ISSUE TITLE
nest generate command not working on node v22.5.1 and typescript v5.5.3

### ISSUE THREAD

**Issue by Neetesh4096** [nestjs/nest-cli#2663] opened 2024-07-23 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Getting error while using nest command to generate module and controller

### Minimum reproduction code

https://github.com/Neetesh4096/nest

### Steps to reproduce

npm i -g @nestjs/cli
npm i -g typescript
npm i
nest g mo message
nest g co message/message --flat

### Expected behavior

It should create a module under a message folder inside src and add controller in the same folder.

### Package version

10.4.2

### NestJS version

10.4.2

### Node.js version

22.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by mezahirecebov** [comment] 2024-07-23 10:37
same issue
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/8616fd5d-f1ff-4b03-a85e-090ef0daa5a2">

**Comment by micalevisk** [comment] 2024-07-23 11:31
Duplicate #2663

**Comment by kamilmysliwiec** [comment] 2024-07-24 07:17
Duplicate of https://github.com/nestjs/nest-cli/issues/2662

**Closed by kamilmysliwiec** 2024-07-24 07:17 UTC
Labels: bug, needs triage
