### ISSUE TITLE
ERROR [I18nService] parsing translation error in 10.3.2

### ISSUE THREAD

**Issue by michaltalaga** [nestjs/nest-cli#2558] opened 2024-03-26 15:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

after updating to 10.3.2 our project fails to process translation files which worked all the way up until now.

### Minimum reproduction code

https://github.com/nestjs/nest-cli/

### Steps to reproduce

our repo is private
steps to repro
npm install
npm run start:dev

### Expected behavior

works as last week but it fails
[Nest] 50208  - 03/26/2024, 4:27:27 PM   ERROR [I18nService] parsing translation error
[Nest] 50208  - 03/26/2024, 4:27:27 PM   ERROR [I18nService] Error: ENOENT: no such file or directory, stat 'xxxxxxxxxxxx\src\backend\dist\i18n'
[Nest] 50208  - 03/26/2024, 4:27:27 PM   ERROR [I18nService] parsing translation error
[Nest] 50208  - 03/26/2024, 4:27:27 PM   ERROR [I18nService] Error: ENOENT: no such file or directory, scandir 'xxxxxxxxxxxx\src\backend\dist\i18n'

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOENT: no such file or directory, stat 'xxxxxxxxxxxx\src\backend\dist\i18n'

### Package version

10.3.2

### NestJS version

10.3.4

### Node.js version

18.19.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment] 2024-03-26 15:40
Please provide a minimum reproduction repository. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by michaltalaga** [comment] 2024-03-26 16:31
narrowed it down to:
https://github.com/michaltalaga/nestjs-cli-i18n-issue


git clone
npm install   // this will use "@nestjs/cli": "10.2.0",
npm run start:dev

it will fail

git clone
// change to "@nestjs/cli": "10.1.18",
npm install
npm run start:dev

it will work

**Comment by michaltalaga** [comment] 2024-03-26 16:37
may be a red herring but it has something to do with nest-cli.json

**Comment by micalevisk** [comment] 2024-03-26 16:39
I just tested your repository with both versions and got the same output:

![image](https://github.com/nestjs/nest-cli/assets/13461315/49a627ab-55f7-45aa-943b-9409fae0e1e7)

so that might be related with Windows. I tested on linux

**Comment by michaltalaga** [comment] 2024-03-26 17:07
that is possible. it worked till 10.1.18 - no issues tho 

if I use the default nest-cli.json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true
  }
}
it breaks even on 10.1.18 

so something around those options must be causing the problem
is there a way I can do verbose logging maybe?

**Comment by micalevisk** [comment] 2024-03-26 17:38
yeah, now I got that error

`Error: ENOENT: no such file or directory, scandir '/tmp/nestjs-cli-i18n-issue/dist/i18n/'`

**Comment by micalevisk** [comment] 2024-03-26 17:40
but it looks like to be related with `nestjs-i18n` package

unless you manage to find a working version of `@nestjs/cli`, of course

**Comment by micalevisk** [comment] 2024-03-26 18:42
just found this: https://github.com/toonvanstrijp/nestjs-i18n/issues/96

isn't the same thing?

**Comment by michaltalaga** [comment] 2024-03-26 19:14
tried out. no luck

**Comment by micalevisk** [comment] 2024-03-26 19:17
to recap, it works when you have that `assets` as in your repository, in your `nest-cli.json`?

**Comment by michaltalaga** [comment] 2024-03-27 08:42
to recap: 

starting in version 10.2.0 following nest-cli.json fails on windows

```
{
  "language": "ts",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "assets": [
      "**/*.html",
      "**/*.otf",
      "i18n/**/*",
      "**/*.json"
    ]
  }
}
```

**Comment by kamilmysliwiec** [comment] 2024-07-02 06:39
Duplicate of https://github.com/nestjs/nest-cli/issues/2429

**Closed by kamilmysliwiec** 2024-07-02 06:39 UTC
Labels: bug, needs triage
