### ISSUE TITLE
Invalid script: pnpm lint

### ISSUE THREAD

**Issue by Chen-913** [nestjs/nest-cli#2759] opened 2024-10-21 13:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tried to create a project using nest/cli within a certain folder. After the creation was complete, I wanted to run `pnpm lint` to format my code, but it gave me a warning and prevented this action.

```bash
pnpm lint

> fail-to-lint@0.0.1 lint /Users/good-man/Desktop/personal-workspace/fail-to-lint
> eslint "{src,apps,libs,test}/**/*.ts" --fix

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.3

Please only submit bug reports when using the officially supported version.

=============
```

### Minimum reproduction code

https://github.com/Chen-913/fail-to-lint

### Steps to reproduce

1. `cd ./some-dir`
2. `nest new my-project -p pnpm`
something happen...
<img width="500" alt="image" src="https://github.com/user-attachments/assets/9da6c2eb-50ca-4e16-b315-252d567ba455">

3. `cd fail-to-lint & pnpm install`
4. `pnpm lint`

### Expected behavior

I hope that pnpm lint can work properly.
I noticed some differences in the CLI-generated package.json. When I run nest new demo on my computer to generate a project, the TypeScript version in the package.json is always ^5.1.3. You can see this in the repository link I provided.

However, when I use the same CLI version on [my StackBlitz project](https://stackblitz.com/edit/stackblitz-starters-1wc1wy?file=demo%2Fpackage.json) , the generated TypeScript version is higher. I’m not sure why this is happening. Additionally, the ESLint version has also changed from version 8 to 9. I originally thought that NestJS intentionally kept ESLint at version 8, but it seems there’s a discrepancy compared to what I expected.

I hope this information helps a bit. Thanks!

### Package version

10.4.5

### NestJS version

^10.0.0

### Node.js version

v18.20.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

1. `pnpm@9.12.1`
2. Apple M2 Pro
3. macOS Sonoma 14.5

**Comment by micalevisk** [comment] 2024-10-21 13:34
this has nothing to do with PNPM btw

the current version of the app generated by `nest new` is broken because the installed typescript version (the latest one, v5.6.3) is not compatible with the latest version of ESLint typescript plugin

To fix that, downgrade `typescript` or wait the next release of `@typescript-eslint/eslint-plugin`

**Comment by micalevisk** [comment] 2024-10-21 13:35
duplicate of https://github.com/nestjs/schematics/issues/1909

**Closed** 2024-10-21 13:40 UTC
Labels: bug, needs triage
